workspace:
  base: /test
  path: task-runner

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    environment:
     - DOCUMENT_ROOT=/test/task-runner

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    volumes:
      - /cache:/cache
    commands:
      - composer install

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:5.6}
    commands:
      # Reset permission since installation runs as root. @todo Fix this.
      - mkdir -p tests
      - chown -R 1000:1000 tests
      - chmod -R 777 /tmp
      - useradd -u 1000 -m -s /bin/bash web
      - su web -c"./vendor/bin/phpunit"

matrix:
  IMAGE_PHP:
    - fpfis/httpd-php-dev:5.6
    - fpfis/httpd-php-dev:7.1
