language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin
    - COMPOSER_MEMORY_LIMIT=2G

install:
  - composer self-update
  - composer install

script:
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/bin/grumphp run
  - ./vendor/bin/phpunit

notifications:
  email: false
