runner:
  bin-dir: "./vendor/bin"

drupal:
  core: "8"
  root: "build"
  # The "root_absolute" is derived at runtime.
  # @see \EC\OpenEuropa\TaskRunner\Commands\DrupalCommands::initializeDrupalRuntimeConfiguration()
  root_absolute: ~
  base_url: "http://127.0.0.1:8888"
  site:
    name: "Site name"
    mail: "info@example.org"
    profile: "standard"
    update: "false"
    locale: "en"
  account:
    name: "admin"
    password: "admin"
    mail: "admin@example.org"
  database:
    host: "127.0.0.1"
    port: "3306"
    name: "drupal"
    user: "root"
    password: "root"
  drush:
    options:
      ignored-directories: "${drupal.root}"
  settings:
    conf:
      file_scan_ignore_directories:
        - "node_modules"
        - "bower_components"
        - "vendor"
        - "${drupal.root}"
  post_install: []

github:
  token: ~
