# ---------------------------------
# Default Task Runner configuration
# ---------------------------------

# Global Task Runner settings.
runner:
  bin_dir: "./vendor/bin"

# Drupal-related setting values.
# All default values below refers to Drupal 8.
# For Drupal 7 projects override them as necessary.
drupal:
  core: "8"
  root: "build"
  # The "root_absolute" is derived at runtime.
  # @see \EC\OpenEuropa\TaskRunner\Commands\DrupalCommands::setRuntimeConfig()
  root_absolute: ~
  base_url: "http://127.0.0.1:8888"

  # Basic Drupal site information.
  site:
    name: "Site name"
    mail: "info@example.org"
    profile: "standard"
    update: "false"
    locale: "en"
    sites_subdir: "default"

  # Administrator account information.
  account:
    name: "admin"
    password: "admin"
    mail: "admin@example.org"

  # Database settings.
  database:
    host: "127.0.0.1"
    port: "3306"
    name: "drupal"
    user: "root"
    password: "root"

  # Local Drush settings file will be generated by following default values.
  drush:
    options:
      ignored-directories: "${drupal.root}"
      uri: "${drupal.base_url}"

  # Following lines will be converted in PHP and appended to default.settings.php.
  settings:
    conf:
      file_scan_ignore_directories:
        - "node_modules"
        - "bower_components"
        - "vendor"
        - "${drupal.root}"

  # List of shell commands to be before and after the site installation.
  # You can use same syntax as the "commands:" below or simply calling a shell command.
  # Configuration token replacement is supported too.
  pre_install: []
  post_install: []

# GitHub configuration values.
github:

  # GitHub OAuth token.
  token: ~

# List of dynamically-defined commands.
commands: []